#include "DeflateCompressor.hpp"

#include "Huffman.hpp"
#include "compressor.hpp"

namespace compressor {
namespace core {

/**
 * @brief Using Deflate and Huffman to compress data
 *
 * @param original_data
 * @return CompressorResult
 */
CompressorResult DeflateCompressor::compress(
    const std::vector<uint8_t>& original_data) {
    // Preparation
    CompressorResult result;
    result.original_size = original_data.size();

    // Calaulate the time cost
    auto start_time = std::chrono::high_resolution_clock::now();

    /* 1. Generate byte stream */
    std::vector<algorithm::Token> tokens =
        algorithm::Deflate::compress(original_data);

    /* 2. Serialize the token to intermediate byte stream */
    std::vector<uint8_t> intermediate_bytes = serializeTokens(tokens);

    /* 3. Huffman recompress */
    result.data = algorithm::Huffman::compress(intermediate_bytes);

    // Accomplish compression
    auto end_time = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double, std::milli> elapsed = end_time - start_time;

    // Fill the result
    result.compressed_size = result.data.size();
    result.compression_ratio =
        static_cast<double>(result.compressed_size) / result.original_size;
    result.time_ms = elapsed.count();

    return result;
}

/**
 * @brief Decompress API
 *
 * @param compressed_data
 * @return CompressorResult
 */
CompressorResult DeflateCompressor::decompress(
    const std::vector<uint8_t>& compressed_data) {
    // Preparation
    CompressorResult result;
    result.compressed_size = compressed_data.size();

    // Calculate the time cost
    auto start_time = std::chrono::high_resolution_clock::now();

    // Decompress the compressed data
    /* 1. Huffman decompress compressed data */
    std::vector<uint8_t> intermediate_bytes =
        algorithm::Huffman::decompress(compressed_data);

    /* 2. Deserialize the byte stream to Token stream */
    std::vector<algorithm::Token> tokens =
        deserializeTokens(intermediate_bytes);

    /* 3. Deflate decompress */
    result.data = algorithm::Deflate::decompress(tokens);

    // Accomplish decompression and fill the result
    auto end_time = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double, std::milli> elapsed = end_time - start_time;

    result.original_size = result.data.size();
    result.compression_ratio =
        static_cast<double>(result.compressed_size) / result.original_size;
    result.time_ms = elapsed.count();

    return result;
}

// ---------------------------------------------------------
// Private serialization and deserialization method
// ---------------------------------------------------------
/**
 * @brief Serialize the Token stream generated by Deflate to byte stream for
 *        Huffman to compress
 *
 * @param tokens
 * @return std::vector<uint8_t>
 */
std::vector<uint8_t> DeflateCompressor::serializeTokens(
    const std::vector<algorithm::Token>& tokens) {
    // Preparation
    std::vector<uint8_t> res;
    res.reserve(tokens.size() * 3);

    // Iterate through the token flow
    for (const auto& t : tokens) {
        if (t.is_literal) {
            res.push_back(1);
            res.push_back(static_cast<uint8_t>(t.value));
        } else {
            res.push_back(0);
            res.push_back(static_cast<uint8_t>(t.value >> 8));
            res.push_back(static_cast<uint8_t>(t.value & 0xFF));
            res.push_back(static_cast<uint8_t>(t.position >> 8));
            res.push_back(static_cast<uint8_t>(t.position & 0xFF));
        }
    }
    return res;
}

/**
 * @brief
 *
 * @param data
 * @return std::vector<algorithm::Token>
 */
std::vector<algorithm::Token> DeflateCompressor::deserializeTokens(
    const std::vector<uint8_t>& data) {
    std::vector<algorithm::Token> tokens;
    size_t i = 0;
    while (i < data.size()) {
        uint8_t flag = data[i++];
        if (flag == 1) {
            tokens.push_back({true, data[i++], 0});
        } else if (flag == 0) {
            uint16_t length =
                (static_cast<uint16_t>(data[i]) << 8) | data[i + 1];
            i += 2;
            uint16_t distance =
                (static_cast<uint16_t>(data[i]) << 8) | data[i + 1];
            i += 2;
            tokens.push_back({false, length, distance});
        }
    }
    return tokens;
}

}  // namespace core
}  // namespace compressor