#!/usr/bin/env python3
"""Build canonical web phrase tables into ``src/gui/engine/web_dict_embedded.py``."""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
SRC_DICT = ROOT / "resources" / "dict"

from gui.engine.web_dict import sort_phrases_for_matching  # noqa: E402
OUT_PATH = ROOT / "src" / "gui" / "engine" / "web_dict_embedded.py"
_SHARED_FILE = "shared_phrases.txt"
_MIN_LEN = 3

KIND_FILES = (
    ("HTML", "web_phrases_html.txt"),
    ("CSS", "web_phrases_css.txt"),
    ("JS", "web_phrases_js.txt"),
    ("JSON", "web_phrases_json.txt"),
)


def _parse_txt(path: Path) -> list[str]:
    lines: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if len(s.encode("utf-8")) < _MIN_LEN:
            continue
        lines.append(s)
    return lines


def _merge_kind(kind_file: str, shared: list[str]) -> list[str]:
    kind_lines = _parse_txt(SRC_DICT / kind_file)
    seen: set[str] = set()
    merged: list[str] = []
    for s in kind_lines + shared:
        if s in seen:
            continue
        seen.add(s)
        merged.append(s)
    return sort_phrases_for_matching(merged)


def _repr_bytes(b: bytes) -> str:
    return repr(b)


def main() -> int:
    missing = [name for _, name in KIND_FILES if not (SRC_DICT / name).is_file()]
    if missing:
        print("Missing dict sources:", ", ".join(missing), file=sys.stderr)
        return 1

    shared_path = SRC_DICT / _SHARED_FILE
    shared = _parse_txt(shared_path) if shared_path.is_file() else []
    if not shared:
        print(f"Warning: no shared phrases from {shared_path}", file=sys.stderr)

    phrases: dict[str, list[str]] = {}
    hasher = hashlib.sha256()
    for kind, filename in KIND_FILES:
        lines = _merge_kind(filename, shared)
        if not lines:
            print(f"Empty phrase list after merge: {filename}", file=sys.stderr)
            return 1
        phrases[kind] = lines
        hasher.update(kind.encode("ascii"))
        for line in lines:
            hasher.update(line.encode("utf-8"))
            hasher.update(b"\n")

    content_hash = hasher.hexdigest()
    parts = [
        '"""Canonical web resource phrase tables (build artifact).',
        "",
        "Generated by scripts/embed_web_dict.py from resources/dict/*.txt",
        "and shared_phrases.txt (merged into each kind).",
        "Do not edit by hand. Re-run embed after changing source phrase files.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "REVISION = 2",
        f'CONTENT_HASH = "{content_hash}"',
        "",
        "PHRASES: dict[str, tuple[bytes, ...]] = {",
    ]
    for kind, _ in KIND_FILES:
        items = ", ".join(_repr_bytes(s.encode("utf-8")) for s in phrases[kind])
        parts.append(f'    "{kind}": ({items}),')
    parts.append("}")
    parts.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_PATH} ({content_hash[:12]}…)")
    for kind, _ in KIND_FILES:
        print(f"  {kind}: {len(phrases[kind])} phrases (+{len(shared)} shared pool)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
